<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Cryptography Utility</Description>
    <OutputType>Exe</OutputType>
    <Title>Crypto</Title>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TNT.ArgumentParser" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TNT.Cryptography\TNT.Cryptography.csproj" />
  </ItemGroup>

</Project>
